### ISSUE TITLE
«Argument 1 passed to Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\AttributeProvider::getByAttributeCode() must be of the type string, null given, called in vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php on line 92»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [vegandthecity/magento#19]
[veg.mage2.pro/shop/was-dazugehort.html](https://veg.mage2.pro/shop/was-dazugehort.html)

![01](https://user-images.githubusercontent.com/83204/79049961-b1c21e80-7c48-11ea-9b75-4c7a62f29597.png)

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/27112

**Comment by dmitrii-fediuk** [comment]
Fixed by https://github.com/magento/magento2/issues/27112#issuecomment-606175216

**Comment by Alexander-Pop** [comment]
same error still appears in 2.3.5 magento/magento-cloud-metapackage

**Comment by klimyflorez** [comment]
Here's I used to fix this issue on Magento 2.4.0:

etc/di.xml

<type name="Magento\Elasticsearch\SearchAdapter\Query\Builder\Sort">
    <arguments>
        <argument name="skippedFields" xsi:type="array">
            <item name="null" xsi:type="string"></item>
        </argument>
    </arguments>
</type>
